language: ruby
script: bundle exec middleman build
rvm:
  - 2.4.1
env:
  global:
  - GIT_COMMITTER_NAME=Yuichiro Someya
  - GIT_COMMITTER_EMAIL=ayemos.y@gmail.com
  - GIT_AUTHOR_NAME=Yuichiro Someya
  - GIT_AUTHOR_EMAIL=ayemos.y@gmail.com
  - secure: brJVv/wgLi5f0erPQjmp3223HahkOi2+lv8mJeGs51yPcfjxO1O//CSZmhdKRw0qQD8b+bI5dMLL8iObr3rxcwdMd9iE0ERayAcVdEJgXrXfGY0nJZGjH0qP9rll+tDsVA0++DSSJn8dZeJGSs0rW4adCe17Fo/1mBzoaCGm9SSs1SWVaa1nKV1Xe0b37Bwb9V9KNCLbpVfEVsgn1w5Zb1l5HJMK+8gQo8Z7cbkklqv8HSq302igWQprE3mU/KH5IhjeVqkbxy+m7Nbybskz3vffF+wPjWkgG+EHxsOx3ab9AGXyQkkcdstHUy3w4nmQCi6UZP0F+RDx21MRDy7SRk8Ns8Q2X0mG3efL+shPqeJvTDTpnoOPcvy61Eod5hGCE27WG4tD5txPI/Qih2L/D+DjHUCO3JA9gMCXvzGoTZ3ilV1OUYnbpqZNofTgL+tIM8Y21W6vXWA1DDVuvRhPQwOHkVqkRIdUD3Uk+SuYzxD9w/7D+7Kc0kI60iUxiq0oA0D1/AogctfQnVyIa9UYjQNzSluwobr2TzsQEqi7Qm5wTGMhr1zks5dSBeUASpOYTb7SroYgp6vV4mycYvea4lJ1JR/+6f8w4XPMRAcyMFxNji+9hDfGvvaZRdwzD1zI+R+yDVY2B5y6EIbvWqQ4sFfS4HH08rWMvk86XCQ3hlQ=
before_script:
- git clone --quiet https://github.com/ayemos/source.leather-port.git
- git clone --quiet https://github.com/ayemos/leather-port.git build
after_success:
- cd build
- git add -A
- git commit -m 'Update'
- '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/ayemos/leather-port.git
  master'
